CREATE TABLE `imported_list` (
  `id` int NOT NULL AUTO_INCREMENT,
  `owner_id` int NOT NULL DEFAULT '0',
  `owner_ally_ids` varchar(45) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `holder` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `holder_id` int DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `C1` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `C2` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `C3` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `C4` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `C5` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `C6` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `C7` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `C8` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `C9` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `C10` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `C11` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `C12` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `C13` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `C14` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `C15` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `C16` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8_unicode_ci;
